-- For running views
select * from orderproduct_vew;
select * from customerorder_vew;
select * from productvendor_vew;
select * from ordershipper_vew;
select * from employee_vew;
select * from recentOrders_vew;
select * from customers_vew;
select * from products_vew;
select * from products_from_order_vew;
